on:
  push:
# branches:
#   - main
# tags:
#   - v*

name: Build

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version tag
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          EPOCH_TIME=$(date +%s)
          echo "VERSION=$SHORT_COMMIT_HASH-$EPOCH_TIME" >> $GITHUB_ENV

      - name: Install ko
        run: make ko

      - name: Build and push image using Make
        run: make build.push
        env:
          REGISTRY: ghcr.io/dbirks/external-dns
